Introduce basic pre/post processor logic
lvkdotsh/logger pull request #96
Opened 2022-02-13 22:59 UTC by Antony1060

Closes #93

2022-02-13 23:01 UTC, Antony1060 commented
Need to fix test coverage, it has some weird artifacts

2022-02-15 22:10 UTC, svemat01 approved these changes
LGTM but wait for another review

2022-02-16 14:43 UTC, lucemans commented on src/index.ts
> +
JSDocs?

2022-02-16 14:43 UTC, lucemans requested changes

2022-02-16 14:43 UTC, lucemans commented on src/index.ts
> +
JSDocs?

2022-02-16 18:51 UTC, Antony1060 commented on src/index.ts
> +
Sowwy

2022-02-16 20:40 UTC, lucemans approved these changes
LGTM

2022-02-16 20:40 UTC, merged